//
// Created by edi on 2/5/21.
//

#ifndef POWEROVERRIDE_PUBLIC_INC_POWEROVERRIDE_COMMON_H_
#define POWEROVERRIDE_PUBLIC_INC_POWEROVERRIDE_COMMON_H_

#define _POWEROVERRIDE_STRINGIFY(x) #x
#define POWEROVERRIDE_STRINGIFY(x) _POWEROVERRIDE_STRINGIFY(x)
#define _POWEROVERRIDE_CONCAT(x, y) x##y
#define POWEROVERRIDE_CONCAT(x, y) _POWEROVERRIDE_CONCAT(x,y)
#define POWEROVERRIDE_NAMESPACE(funcname) POWEROVERRIDE_CONCAT(_private_c_,POWEROVERRIDE_CONCAT(funcname,__LINE__))
#endif //POWEROVERRIDE_PUBLIC_INC_POWEROVERRIDE_COMMON_H_
